include: '/templates/renovate-dind.gitlab-ci.yml'

stages:
  - test
  - deploy
  - release

renovate:dry-run:
  only:
    - branches@renovate-bot/renovate-runner
  except:
    - schedules
  script:
    - renovate --dry-run=true $RENOVATE_EXTRA_FLAGS

release:
  image: renovate/node:14.17.3@sha256:9eb170c8a64f58da23f39c57cd87d8fb4a201cadf4e447471f6bf7c754a88c64
  stage: release
  before_script:
    - npm ci
  script:
    - npx --no-install semantic-release
  only:
    - main
