include: '/templates/renovate-dind.gitlab-ci.yml'


renovate:dry-run:
  only:
    - branches@renovate-bot/renovate-runner
  except:
    - schedules
  script:
    - renovate --dry-run=true $RENOVATE_EXTRA_FLAGS
