include: '/templates/renovate-dind.gitlab-ci.yml'

stages:
  - test
  - deploy
  - release

renovate:dry-run:
  script:
    - renovate --dry-run=true $RENOVATE_EXTRA_FLAGS
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

release:
  image: renovate/node:16.13.1@sha256:d8e9b667d6bcc3d3c27dcbbf5b80c711b0046089c61897689c9e1c68e35655bf
  stage: release
  cache: []
  before_script:
    - npm ci
  script:
    - npx --no-install semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
