include: '/templates/renovate-dind.gitlab-ci.yml'

variables:
  RENOVATE_DOCKER_IMAGE_PREFIX: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/renovate
  CI_IMAGE_NODE: renovate/node:16.13.1@sha256:8f4bc1bd2b2e539e54c0555462f00fe877ea67bc4edbc0364f87967b085f9f3f

image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/${CI_RENOVATE_IMAGE}

services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/${CI_RENOVATE_SERVICE}
    alias: docker

stages:
  - test
  - deploy
  - release

renovate:dry-run:
  script:
    - renovate --dry-run=true $RENOVATE_EXTRA_FLAGS
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

release:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/${CI_RENOVATE_NODE}
  stage: release
  cache: []
  before_script:
    - npm ci
  script:
    - npx --no-install semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
