include: '/templates/renovate-dind.gitlab-ci.yml'

stages:
  - test
  - deploy
  - release

renovate:dry-run:
  rules:
    - if: '$CI_COMMIT_BRANCH'
  script:
    - renovate --dry-run=true $RENOVATE_EXTRA_FLAGS

release:
  image: renovate/node:14.17.5@sha256:f31e565f27fa2832e26be5376ea94ea93d5c69dbe949a65fcba990a364670483
  stage: release
  cache: []
  before_script:
    - npm ci
  script:
    - npx --no-install semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
