include: '/templates/renovate-dind.gitlab-ci.yml'

stages:
  - test
  - deploy
  - release

renovate:dry-run:
  only:
    - branches@renovate-bot/renovate-runner
  except:
    - schedules
  script:
    - renovate --dry-run=true $RENOVATE_EXTRA_FLAGS

release:
  image: renovate/node:14.17.3@sha256:2d441eba4395f727ecda95de15497cbace9bf2f5b776225b5e588a91deb15ce4
  stage: release
  before_script:
    - npm ci
  script:
    - npx --no-install semantic-release
  only:
    - main
