include: '/templates/renovate-dind.gitlab-ci.yml'

stages:
  - test
  - deploy
  - release

renovate_dry-run:
  variables:
    RENOVATE_TOKEN: $CI_JOB_TOKEN
    RENOVATE_USERNAME: $GITLAB_USER_LOGIN
    RENOVATE_BRANCH_PREFIX: ${GITLAB_USER_LOGIN}-renovate/
    RENOVATE_X_SERVER_VERSION: $CI_SERVER_VERSION
  script:
    - echo "running on GitLab v${RENOVATE_X_SERVER_VERSION}"
    - renovate --dry-run=true $RENOVATE_EXTRA_FLAGS
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

release:
  image: renovate/node:14.17.5@sha256:f31e565f27fa2832e26be5376ea94ea93d5c69dbe949a65fcba990a364670483
  stage: release
  cache: []
  before_script:
    - npm ci
  script:
    - npx --no-install semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
