include: '/templates/renovate-dind.gitlab-ci.yml'

stages:
  - test
  - deploy
  - release

renovate:dry-run:
  only:
    - branches@renovate-bot/renovate-runner
  except:
    - schedules
  script:
    - renovate --dry-run=true $RENOVATE_EXTRA_FLAGS

release:
  image: renovate/node:14.17.2@sha256:048b7f09fbd92fcbb4381c08a8687e767a525c07d148bbe4abdd0d8528f2d80d
  stage: release
  before_script:
    - npm ci
  script:
    - npx --no-install semantic-release
  only:
    - main
