include: '/templates/renovate-dind.gitlab-ci.yml'

stages:
  - test
  - deploy
  - release

renovate:dry-run:
  only:
    - branches@renovate-bot/renovate-runner
  except:
    - schedules
  script:
    - renovate --dry-run=true $RENOVATE_EXTRA_FLAGS

release:
  image: renovate/node:14.17.5@sha256:f04dbd5a28f36c5b947c4a4773b5b1cf50e6ca3469ee4fbd0fea1acb48dc3cd5
  stage: release
  before_script:
    - npm ci
  script:
    - npx --no-install semantic-release
  only:
    - main
