include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:27.31.7-slim@sha256:c002b4f447ecd6dbddcf1c2ad5928d63e4e48c351cea229db873bfc7786471dd

services:
  - docker:20.10.9-dind@sha256:d20f0866ee1aca6b0eb7bc8bdb0d0c938721c7f79219b1d3bc1aa58666928586

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
