include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:24.89.3-slim@sha256:b0beeec79a52ad4d6787b21b2b90e92055f36d655e90abfba1dc48426418a3ef

services:
  - docker:20.10.5-dind@sha256:551525fd35e48d04f8b44f23db5af2b7db6251f92698d77a857eccacfa2724fe

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
