include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.47.2-slim@sha256:51fb74f4b8e06ce3b4970c0b92a45f4ce22f8f59a5fa87cf36a498182f024b8a

services:
  - docker:20.10.7-dind@sha256:4e1e22f471afc7ed5e024127396f56db392c1b6fc81fc0c05c0e072fb51909fe

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
