include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:24.98.5-slim@sha256:ba17b09c74fb617d6da74aefdf4db327631d8475b37c8b735e7eb1cad4172fe6

services:
  - docker:20.10.5-dind@sha256:e4ecd4e9ad5140d584669451b05e406d8cf7603e51972b862178ad93c38b2b08

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
