include: '/templates/_common.gitlab-ci.yml'

image: ${CI_RENOVATE_IMAGE}

services:
  - ${CI_RENOVATE_SERVICE}

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
  CI_RENOVATE_SERVICE: docker:20.10.12-dind@sha256:1f50d3a86f7035805843779f803e81e8f4ce96b62ed68fc70cdcf4922f43470b
  CI_RENOVATE_IMAGE: renovate/renovate:31.2.2-slim@sha256:d753aee84a6d396906ed668899d5a5ae693650e2fc39b931909a2e57b90b6201
