include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:27.15.0-slim@sha256:1cedf259a5b7a0292886981d75332391ecad44f85d607b305aa7961dc21bd01b

services:
  - docker:20.10.8-dind@sha256:1efacb06edbb1e2bd4a39dcc69883866c7dd98562a49fa97d7d29c2da1c3974f

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
