include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.27.0-slim@sha256:5847248ecd11f3d9c5480e7c2250012717b58ea1e82da2a23f5e45e783a89418

services:
  - docker:20.10.6-dind@sha256:aa1e1fab842a35f16cf6e8fcb82b77b29be46f6aa8cd0fe69db0908940256be7

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
