include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:24.27.3-slim

services:
  - docker:20.10.2-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
