include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:28.1.8-slim@sha256:7c5f54e30ed95622c567f25ce5d2cc3d9e383927f4a55adb29269e3d9f0959ea

services:
  - docker:20.10.9-dind@sha256:d842418d21545fde57c2512681d9bdc4ce0e54f2e0305a293ee20a9b6166932b

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
