include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.56.11-slim@sha256:eff5e0731887db81b94b3e82a367126ed58cb11deb51b98d6bc816fab02cfcf5

services:
  - docker:20.10.7-dind@sha256:b36fdccb118bfaa8d5026da5183a077b87bc790051fcd2c5686bfb8f7fa2563c

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
