include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:24.98.2-slim@sha256:3c53607ad383a2fbe4fcc40c824e82377617686f4e47cc311ac9f9112db8d0ae

services:
  - docker:20.10.5-dind@sha256:1f37f241857fba20adf6a1c0ccdcfeccd832a4e6d591a8f1d1d65b821b8891f0

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
