include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:27.20.0-slim@sha256:693269e446588869d563017d565c7f41d3716edd76cd8bb1575b43a80c1b33f9

services:
  - docker:20.10.8-dind@sha256:1efacb06edbb1e2bd4a39dcc69883866c7dd98562a49fa97d7d29c2da1c3974f

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
