include: '/templates/_common.gitlab-ci.yml'

image: ${CI_RENOVATE_IMAGE}

variables:
  CI_RENOVATE_IMAGE: renovate/renovate:31.36.0@sha256:be466dedca7d39bdfa218253313a258f21e5da7f175ee0901d47bb36cb276b0d
