include: '/templates/_common.gitlab-ci.yml'

image: ${CI_RENOVATE_IMAGE}

services:
  - name: ${CI_RENOVATE_SERVICE}
    alias: docker


variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
  CI_RENOVATE_SERVICE: docker:20.10.12-dind@sha256:1f50d3a86f7035805843779f803e81e8f4ce96b62ed68fc70cdcf4922f43470b
  CI_RENOVATE_IMAGE: renovate/renovate:31.24.1-slim@sha256:2adaad3acffe48e7b55485bf8157069c7ee322aea131b073ccd717549d816d89
