include: '/templates/_common.gitlab-ci.yml'

image: ${CI_RENOVATE_IMAGE}

variables:
  CI_RENOVATE_IMAGE: renovate/renovate:31.7.0@sha256:4888c8a47167c8c5fe0539be4e072cd6b755c60c50d9b76e6db8ce42fe3443b4
