include: '/templates/_common.gitlab-ci.yml'

image: ${CI_RENOVATE_IMAGE}

variables:
  CI_RENOVATE_IMAGE: renovate/renovate:29.23.2@sha256:fd4045cd7e8e7cc07231ee3685d53842b11825ff630d7834fea364f7faef55e4
