include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:27.22.0-slim@sha256:afae7632bfbd7ad326eff7a64dbd16b42bd650bf64368988c25551a4ba230935

services:
  - docker:20.10.8-dind@sha256:1efacb06edbb1e2bd4a39dcc69883866c7dd98562a49fa97d7d29c2da1c3974f

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
