include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.53.3-slim@sha256:63eceaca7713a6143db1c5e251aff1712edfb6af1414709e328bc86d3352e87f

services:
  - docker:20.10.7-dind@sha256:4e1e22f471afc7ed5e024127396f56db392c1b6fc81fc0c05c0e072fb51909fe

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
