include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.7.1-slim@sha256:7a9f4153159c9a05b03f1dddb11d55b88035dd4c660f3fe96b87a1364d6fddc8

services:
  - docker:20.10.6-dind@sha256:aa1e1fab842a35f16cf6e8fcb82b77b29be46f6aa8cd0fe69db0908940256be7

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
