include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:27.6.2-slim@sha256:6a121095a177bbf990e38848ecd7f40b07d1ce01f31247ce5fd343bea54e6f8d

services:
  - docker:20.10.8-dind@sha256:1efacb06edbb1e2bd4a39dcc69883866c7dd98562a49fa97d7d29c2da1c3974f

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
