include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.49.3-slim@sha256:8f7f1bb296d393db112f8ef0c0dbeace79793d0cd1d22b88ddb32f5ea1278176

services:
  - docker:20.10.7-dind@sha256:4e1e22f471afc7ed5e024127396f56db392c1b6fc81fc0c05c0e072fb51909fe

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
