include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.29.1-slim@sha256:39459c42b7d6fd7a94c611e2c0ea4a02c71836c983c457742176ed6dbc3fbdef

services:
  - docker:20.10.6-dind@sha256:aa1e1fab842a35f16cf6e8fcb82b77b29be46f6aa8cd0fe69db0908940256be7

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
