include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.51.1-slim@sha256:b142e682c82c0a8917d6e41f9928adafcec92306bb2df8ec459bee0786aed06c

services:
  - docker:20.10.7-dind@sha256:4e1e22f471afc7ed5e024127396f56db392c1b6fc81fc0c05c0e072fb51909fe

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
