include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:28.11.2-slim@sha256:0fd54178edd3c7f9f9cdfcfd4ac6f017c9ac38cfb65188c57257a69fb5a27be1

services:
  - docker:20.10.10-dind@sha256:4affae8ac27539b74e27ac4f2d6662902a328340c218336944bab7e482244cc4

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
