include: '/templates/_common.gitlab-ci.yml'

image: ${CI_RENOVATE_IMAGE}

variables:
  CI_RENOVATE_IMAGE: renovate/renovate:31.13.0@sha256:aed81ca5631a0c5c6ea56ba3dc784f164a1ffb650066c151dbe21b06afeb66df
