include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.7.7-slim@sha256:3121595dc861a8b6ea5741f66d96f37d568a2715129e08efe707360151cb4bca

services:
  - docker:20.10.6-dind@sha256:aa1e1fab842a35f16cf6e8fcb82b77b29be46f6aa8cd0fe69db0908940256be7

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
