include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:24.97.3-slim@sha256:fb66e000284e0c5b82472f0b709e4625766f50b8e18bdf37ccbdb03933c66638

services:
  - docker:20.10.5-dind@sha256:1f37f241857fba20adf6a1c0ccdcfeccd832a4e6d591a8f1d1d65b821b8891f0

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
