include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:27.8.2-slim@sha256:40d7691eae1e06e4af77cc35552a10d064044728a4e8da3642027ad6b4e27634

services:
  - docker:20.10.8-dind@sha256:1efacb06edbb1e2bd4a39dcc69883866c7dd98562a49fa97d7d29c2da1c3974f

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
