include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.51.5-slim@sha256:ab4e1c793a4b40cb5890e1505535bc6a6e4f63df6e3dea8e3b6b67be438a6a94

services:
  - docker:20.10.7-dind@sha256:4e1e22f471afc7ed5e024127396f56db392c1b6fc81fc0c05c0e072fb51909fe

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
