include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:28.5.0-slim@sha256:91374ec1ca2540d203b25c26bca7d7bfbfbef75d1cc46a2f2724580932cad7ee

services:
  - docker:20.10.9-dind@sha256:d842418d21545fde57c2512681d9bdc4ce0e54f2e0305a293ee20a9b6166932b

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
