include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.47.4-slim@sha256:541f7c169ed5fcba3abf7e1c0261d49a1b0bab54a3cbf427c8d731427a5a2102

services:
  - docker:20.10.7-dind@sha256:4e1e22f471afc7ed5e024127396f56db392c1b6fc81fc0c05c0e072fb51909fe

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
