include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.21.3-slim@sha256:db778d120c3a54eca086cb7c421422a52a6689371006398e8c7cfb83f7ee8d66

services:
  - docker:20.10.6-dind@sha256:aa1e1fab842a35f16cf6e8fcb82b77b29be46f6aa8cd0fe69db0908940256be7

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
