include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.59.0-slim@sha256:43ff2e7d3ae00bbc2b8ccdc23b8489edd7772c22a086509a0b02396696ade228

services:
  - docker:20.10.7-dind@sha256:b36fdccb118bfaa8d5026da5183a077b87bc790051fcd2c5686bfb8f7fa2563c

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
