include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.52.6-slim@sha256:efad1b1cfd48d1c3371a42a0f47db0a12d1f7a91ca2a0c81670f353cdb239bf0

services:
  - docker:20.10.7-dind@sha256:4e1e22f471afc7ed5e024127396f56db392c1b6fc81fc0c05c0e072fb51909fe

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
