include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.33.5-slim@sha256:691358eaa7a2bfe5298c18175e3a4e03b942fe377c9400723ea707f9bdb0f69d

services:
  - docker:20.10.6-dind@sha256:aa1e1fab842a35f16cf6e8fcb82b77b29be46f6aa8cd0fe69db0908940256be7

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
