include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:27.31.10-slim@sha256:14d2474fc6c2fb251def6c85bccf8d4a8ba35b7ae4d2f16fc308932396ebf375

services:
  - docker:20.10.9-dind@sha256:d20f0866ee1aca6b0eb7bc8bdb0d0c938721c7f79219b1d3bc1aa58666928586

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
