include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.1.3-slim@sha256:55ca047123d8b8dba2277e82b8184e5e6f983b26de1bf8525b10004caef74b02

services:
  - docker:20.10.6-dind@sha256:3d3597b3aebffa08c75c206872af278f9e0df2b9130fded6197bd885000e824d

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
