include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:25.61.0-slim@sha256:311c7f34c9c242e9b1f2ef29e46a3f0a23d1db71f6021089a9884a1ed535dc6d

services:
  - docker:20.10.7-dind@sha256:b36fdccb118bfaa8d5026da5183a077b87bc790051fcd2c5686bfb8f7fa2563c

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
