include: '/templates/_common.gitlab-ci.yml'

image: ${CI_RENOVATE_IMAGE}

variables:
  CI_RENOVATE_IMAGE: renovate/renovate:31.20.0@sha256:072f6daa5303656f88ea78a1cafc2f91eb9ea79e399cbbbd1a74f5f64f7d5e68
